---

- name: Install Video Software Related
  apt: 
    state: latest	
    pkg: "{{ item }}"
  with_items:
    - vlc 
    - browser-plugin-vlc

- name: Install Media Codecs for Ubuntu
  apt:
    state: latest
    pkg: "{{ item }}"
  with_items:
    - ubuntu-restricted-extras

- name: Add the Google Chrome package signing key to apt
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: A040830F7FAC5991

- name: Add the Google Chrome repository
  apt_repository:
    repo: "deb http://dl.google.com/linux/chrome/deb/ stable main"
    state: present

# - name: Add the Dropbox package signing key to apt
#   apt_key:
#     keyserver: pgp.mit.edu
#     id: 5044912E

# - name: Add the Dropbox repository
#   apt_repository:
#     repo: "deb http://linux.dropbox.com/{{ ansible_distribution.lower() }} {{ ansible_distribution_release }} main"
#     state: present

# - name: Install Spotify Client for Linux
#   shell: |
#     apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys BBEBDCB318AD50EC6865090613B00F1FD2C19886
#     echo deb http://repository.spotify.com stable non-free | tee /etc/apt/sources.list.d/spotify.list
#     apt-get update
#     apt-get install spotify-client

- name: Add Spotify Package Signing Key
  apt_key:
    keyserver: "keyserver.ubuntu.com"
    id: BBEBDCB318AD50EC6865090613B00F1FD2C19886

- name: Add Spotify Repo
  apt_repository: 
    repo: "deb http://repository.spotify.com stable non-free"
    state: present

- name: Install Latest Spotify Client
  apt: 
    pkg: spotify-client
    state: latest

- name: Install useful graphical software
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    # - dropbox
    - google-chrome-stable

- name: Remove all of the unnecessary packages that come with Debian and Ubuntu
  apt:
    pkg: "{{ item }}"
    state: absent
  with_items:

    # Games
    - aisleriot
    - four-in-a-row
    - gnome-chess
    - gnome-games
    - gnome-klotski
    - gnome-mahjongg
    - gnome-mines
    - gnome-nibbles
    - gnome-robots
    - gnome-sudoku
    - gnome-tetravex
    - hitori
    - iagno
    - lightsoff
    - quadrapassel
    - swell-foop
    - tali
    - xboard

    # Utilities
    # - bluez
    # - ppp
    # - gnome-orca
    # - gnome-accessibility-themes
    # - vino
    # - espeak-data
    # - libespeak1
    # - icedove
    - thunderbird
    # - totem
    # - totem-common
    # - totem-plugins

- name: Install Home Network Connectivity Packages
  apt:
    pkg: vsftpd
    state: present

- name: Install Dropbox
  include: dropbox.yml
  when: ansible_distribution == 'Ubuntu'
  tags: ["packages", "dropbox"]