---

- name: Install Essential Packages
  become: True
  become_method: sudo
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - git
    - python-pip
    - python-setuptools
    - gitk
    - git-gui

- include: team_viewer.yml

- name: Create Development Tools Directory
  file: 
    path: ~/Dev/tools 
    state: directory